In [1]:
import numpy as np

# simple array types
n1 = np.array([2,4,6,8])

n2 = np.zeros((2,4))

n3 = np.full((7,2), (4))

n4 = np.arange(1, 21, 3)

n5 = np.random.randint(5, 50, 3)

n6 = np.array([[2,2,4,5], [6,7,3,2]])

print(n1, n2, n3, n4, n5, n6)

print("-------------------")

# stacking arrays
print(np.vstack((n1, n2)))

print("-------------------")

print(np.hstack((n5, ([1, 2, 3, 4, 5, 6, 7]))))

print("-------------------")

# joins & diffs

print("intersection of n1 & n2"); print(np.intersect1d(n1, n2))

print("-------------------")

print("diff of n1 & n2"); print(np.setdiff1d(n1, n2))

print("-------------------")

# math

print(np.mean(n1))
print(np.median(n5))
print(np.std(n1)) #standard deviation of n1

[2 4 6 8] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]] [ 1  4  7 10 13 16 19] [41 29 44] [[2 2 4 5]
 [6 7 3 2]]
-------------------
[[2. 4. 6. 8.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------------
[41 29 44  1  2  3  4  5  6  7]
-------------------
intersection of n1 & n2
[]
-------------------
diff of n1 & n2
[2 4 6 8]
-------------------
5.0
41.0
2.23606797749979
