In [26]:
import numpy as np

# simple array types
n1 = np.array([2,4,6,8])

n2 = np.zeros((2,4))

n3 = np.full((7,2), (4))

n4 = np.arange(1, 21, 3)

n5 = np.random.randint(5, 50, 3)

n6 = np.array([[2,2,4,5], [6,7,3,2]])

print(n1, n2, n3, n4, n5, n6)

print("-------------------")

# joining arrays
print(np.vstack((n1, n2)))

print("-------------------")

print(np.hstack((n5, ([1, 2, 3, 4, 5, 6, 7]))))


[2 4 6 8] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]] [[4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]] [ 1  4  7 10 13 16 19] [47 19 43] [[2 2 4 5]
 [6 7 3 2]]
-------------------
[[2. 4. 6. 8.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-------------------
[47 19 43  1  2  3  4  5  6  7]
